# Check the link below to see how you can get the token value
# https://truecharts.org/charts/stable/cloudflared/installation_notes
cloudlflared:
  token: your_token_value
args:
  - tunnel
  - --no-autoupdate
  - run
  - --token
  - your_token_value
