repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: kubitodev
    url: https://charts.kubito.dev

helmfiles:
  - ./cert-manager/helmfile.yaml
  - ./ingress-nginx/helmfile.yaml
  - ./loki-stack/helmfile.yaml
  - ./cloudflared/helmfile.yaml
