repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmfiles:
  - ./cert-manager/helmfile.yaml
  - ./ingress-nginx/helmfile.yaml
